name: Update GitHub Profile Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "17 3 * * *"

jobs:
  stats:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Generate GitHub activity
        uses: cicirello/user-statistician@v1
        with:
          include-title: true
          custom-title: "ChaitanyaXDev · GitHub Activity"
          small-title: true
          colors: dark
          show-border: false

          # Keep only the contribution section.
          hide-keys: general, repositories, languages
          category-order: contributions

          image-file: profile/github-activity.svg

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
